[project]
name = "qnmfits"
dynamic = ["version", "description"]
description = "blah"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  { name = "Lorena Magaña Zertuche", email = "lmaganaz@go.olemiss.edu" }
  { name = "Eliot Finch", email = "efinch@caltech.edu" },
  ]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Astronomy"
  ]
dependencies = [
  "scri>=2022.8.7",
  "sxs >=2022.4.0",
  "tqdm >=4.63.1"
  ]

[project.urls]
Homepage = "https://github.com/sxs-collaboration/qnmfits"
Documentation = "https://qnmfits.readthedocs.io/"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
