[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qnmfits"
version = "0.0.1"
authors = [
  { name="Eliot Finch", email="efinch@star.sr.bham.ac.uk" },
  { name="Lorena Magana Zertuche", email="lmaganaz@go.olemiss.edu"},
]
description = "Fitting of quasinormal modes to ringdown waveforms."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "scri",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/sxs-collaboration/qnmfits"
