[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "qnmfits"
authors = [
  {name = "Eliot Finch", email = "efinch@caltech.edu"},
  {name = "Lorena Magana Zertuche", email = "lmaganaz@go.olemiss.edu"}
  ]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/sxs-collaboration/qnmfits"
